### ISSUE TITLE
`ValueError: error parsing asn1 value: ParseError { kind: ShortData }` inside `load_ocsp_response()`

### ISSUE THREAD

**Issue by tykling** [tykling/certgrinder#581]
```
Traceback (most recent call last):
  File "/opt/certgrinder/virtualenv/bin/certgrinder", line 8, in <module>
    sys.exit(main())
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/certgrinder/certgrinder.py", line 2259, in main
    certgrinder.grind(args)
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/certgrinder/certgrinder.py", line 1835, in grind
    getattr(self, args.method)()
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/certgrinder/certgrinder.py", line 1641, in periodic
    if not self.check_ocsp():
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/certgrinder/certgrinder.py", line 1139, in check_ocsp
    ocsp_response = self.load_ocsp_response(self.ocsp_response_path)
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/certgrinder/certgrinder.py", line 1045, in load_ocsp_response
    return ocsp.load_der_ocsp_response(ocsp_response_data)
  File "/opt/certgrinder/virtualenv/lib/python3.10/site-packages/cryptography/x509/ocsp.py", line 622, in load_der_ocsp_response
    return ocsp.load_der_ocsp_response(data)
ValueError: error parsing asn1 value: ParseError { kind: ShortData }

```

**Comment by tykling** [comment]
this happens when no ocsp response is found on disk
